- name: Download ACME
  get_url: >
    url=https://github.com/hlandau/acme/releases/download/v0.0.20/acmetool-v0.0.20-linux_amd64.tar.gz
    dest=/root/acmetool-v0.0.20.tar.gz
- name: Unzip ACME
  command: >
    tar zxf /root/acmetool-v0.0.20.tar.gz chdir=/root/
    creates=/root/acmetool-v0.0.20-linux_amd64/bin/acmetool
- name: Link ACME
  command: >
    ln -s /root/acmetool-v0.0.20-linux_amd64/bin/acmetool /usr/local/bin/acmetool
    creates=/usr/local/bin/acmetool
- name: Add ACME quickstart file
  template: >
    src=acme_response_file.yaml.j2
    dest=/root/acme_response_file.yaml
    mode=0644
- name: Run ACME quickstart
  command: >
    acmetool quickstart --response-file=/root/acme_response_file.yaml
    creates=/var/lib/acme
- name: Get ACME SSL certificate
  command: >
    acmetool want {{ acme_domain }}
    creates=/var/lib/acme/live/{{ acme_domain }}
  notify:
    - Restart Nginx