---
- name: Configure server
  hosts: all
  sudo: yes
  remote_user: root
  roles:
    - { role: common }
    - { role: postgres }
    - { role: nginx, tags: nginx }
    - { role: acmetool, tags: acme }
    - { role: django, tags: django }