---
- name: Configure server
  hosts: all
  remote_user: root
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - { role: common }
    - { role: postgres }
    - { role: nginx, tags: nginx }
    - { role: acmetool, tags: acme }
    - { role: django, tags: django }