---
- name: Create application user and home
  user: >
    home={{ project.root }}
    name={{ project.user }}
    groups=www-data
    state=present
  tags:
    - user

- name: Change permissions
  shell: chown -R {{ project.user }}:{{ project.user }} {{ project.root }} -R
  tags:
    - user

- name: Create SSH directory
  file: >
    state=directory
    path={{ project.root }}.ssh/
  tags:
  - user

- name: Upload SSH private key
  template: >
    src=ssh_key.j2
    dest={{ project.root }}.ssh/id_rsa
    mode=0600
  tags:
    - user

- name: Change SSH owner
  file: path={{project.root}}.ssh/ owner={{ project.user }} recurse=yes
  tags:
    - user

- name: Change SSH permissions
  file: path={{project.root}}.ssh/ mode=0700 recurse=no
  tags:
    - user
