site_name: My Docs
docs_dir: 'src'
site_dir: 'build'
pages:
  - 'Introduction': index.md
  - 'Configuration': config.md
  - 'Loading data': data.md
  - 'Plugins': plugins.md
  - 'Deployment': deployment.md
